package net.postchain.zkp.plonk

import assertk.assertThat
import assertk.assertions.isEqualTo
import com.google.gson.Gson
import com.google.gson.JsonArray
import net.postchain.common.exception.UserMistake
import net.postchain.gtv.mapper.GtvObjectMapper
import net.postchain.zkp.curve.BLS12381
import net.postchain.zkp.curve.BN128
import net.postchain.zkp.curve.G1Point
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertThrows
import java.math.BigInteger

/**
 * The tests use input data from SnarkJS
 *
 * BN128 tests use proof generated by their fullprocess.js test case.
 *
 * BLS12-381 proofs can't be generated by that test case, at least not without non-trivial modification.
 * A proof was instead manually constructed based on circuit and input in repo:
 * https://github.com/finitology/snarkjs-bls12381-plonk
 */
class PlonkVerifierTest {
    private val gson = Gson()

    val verificationKeyBls12381 = GtvObjectMapper.fromGtv(
            snarkJsVerificationKeyJSONToGtv(
                    gson,
                    javaClass.getResource("/net/postchain/zkp/plonk/bls12381/verification_key.json")!!.readText()
            ),
            PlonkVerificationKey::class.java,
    )

    val verificationKeyBn128 = GtvObjectMapper.fromGtv(
            snarkJsVerificationKeyJSONToGtv(
                    gson,
                    javaClass.getResource("/net/postchain/zkp/plonk/bn128/verification_key.json")!!.readText()
            ),
            PlonkVerificationKey::class.java,
    )

    val validProofBls12381 = PlonkProof.fromGtvArray(
            snarkJsProofJSONToGtv(
                    gson,
                    BLS12381,
                    javaClass.getResource("/net/postchain/zkp/plonk/bls12381/proof.json")!!.readText()
            ),
    )

    val validProofBn128 = PlonkProof.fromGtvArray(
            snarkJsProofJSONToGtv(
                    gson,
                    BN128,
                    javaClass.getResource("/net/postchain/zkp/plonk/bn128/proof.json")!!.readText()
            )
    )

    val validPublicSignalsBls12381 = gson.fromJson(
            javaClass.getResource("/net/postchain/zkp/plonk/bls12381/public.json")!!.readText(),
            JsonArray::class.java
    ).map { it.asBigInteger }.toTypedArray()

    val validPublicSignalsBn128 = gson.fromJson(
            javaClass.getResource("/net/postchain/zkp/plonk/bn128/public.json")!!.readText(),
            JsonArray::class.java
    ).map { it.asBigInteger }.toTypedArray()

    @Test
    fun `Verifies valid BN128 plonk proof successfully`() {
        PlonkVerifier.verifyProof(
                verificationKeyBn128,
                validProofBn128,
                validPublicSignalsBn128
        )
    }

    @Test
    fun `Verifies valid BLS12-381 plonk proof successfully`() {
        PlonkVerifier.verifyProof(
                verificationKeyBls12381,
                validProofBls12381,
                validPublicSignalsBls12381
        )
    }

    @Test
    fun `Throws UserMistake for invalid proof with invalid point`() {
        // Create a proof with an invalid point (A point is not on the curve)
        val invalidProof = PlonkProof(
                G1Point.createG1Point(
                        BN128,
                        BigInteger("99999999999999999999999999999999999999999999999999999999999999999999999999999"),
                        BigInteger("99999999999999999999999999999999999999999999999999999999999999999999999999999"),
                        BigInteger.ONE
                ),
                validProofBn128.B,
                validProofBn128.C,
                validProofBn128.Z,
                validProofBn128.T1,
                validProofBn128.T2,
                validProofBn128.T3,
                validProofBn128.Wxi,
                validProofBn128.Wxiw,
                validProofBn128.evalA,
                validProofBn128.evalB,
                validProofBn128.evalC,
                validProofBn128.evalS1,
                validProofBn128.evalS2,
                validProofBn128.evalZw
        )

        // Expect UserMistake to be thrown with specific message
        val exception = assertThrows<UserMistake> {
            PlonkVerifier.verifyProof(verificationKeyBn128, invalidProof, validPublicSignalsBn128)
        }

        assertThat(exception.message).isEqualTo(
                "Proof commitment A is not a valid point on the curve"
        )
    }

    @Test
    fun `Throws UserMistake for invalid proof with invalid pairing check`() {
        // Create a proof with valid points but invalid values that will fail the pairing check
        val invalidProof = PlonkProof(
                validProofBn128.A,
                validProofBn128.B,
                validProofBn128.C,
                validProofBn128.Z,
                validProofBn128.T1,
                validProofBn128.T2,
                validProofBn128.T3,
                validProofBn128.Wxi,
                validProofBn128.Wxiw,
                // Change evaluation values to make the pairing check fail
                BigInteger("1234567890"),
                BigInteger("1234567890"),
                BigInteger("1234567890"),
                BigInteger("1234567890"),
                BigInteger("1234567890"),
                BigInteger("1234567890"),
        )

        // Expect UserMistake to be thrown with specific message
        val exception = assertThrows<UserMistake> {
            PlonkVerifier.verifyProof(verificationKeyBn128, invalidProof, validPublicSignalsBn128)
        }

        assertThat(exception.message).isEqualTo(
                "Pairing check failed: proof is invalid"
        )
    }

    @Test
    fun `Throws UserMistake for invalid proof with incorrect public signals`() {
        // Use incorrect public signals (wrong number of signals)
        val invalidPubSignals = arrayOf(
                BigInteger("19820469076730107577691234630797803937210158605698999776717232705083708883456"),
                BigInteger("12345")
        )

        // Expect UserMistake to be thrown with specific message
        val exception = assertThrows<UserMistake> {
            PlonkVerifier.verifyProof(verificationKeyBn128, validProofBn128, invalidPubSignals)
        }
        assertThat(exception.message).isEqualTo(
                "Number of public signals does not match verification key"
        )
    }
}
